import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from "next/link";
import Navigation from "@/components/navigation/navigation";
import Footer from "@/components/navigation/footer";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Krzysztof Płonka',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Next.js',
    description: 'The React Framework for the Web',
    url: 'https://krzysztofplonka.pl',
    siteName: 'Next.js',
    images: [
      {
        url: `${process.env.NEXT_PUBLIC_ASSETS_URL}6692021d-5644-44a7-802f-1b9bd7454f70.jpeg`,
      width: 800,
      height: 600,
      },
    ],
locale: 'en_US',
  type: 'website',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        <div className="pt-10 min-h-[calc(100vh-300px)]">{children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
