import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from "next/link";
import Navigation from "@/components/navigation/navigation";
import Footer from "@/components/navigation/footer";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Krzysztof Płonka',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Next.js',
    description: 'The React Framework for the Web',
    url: 'https://krzysztofplonka.pl',
    siteName: 'Next.js',
    images: [
      {
        url: 'https://krzysztofplonka.pl/_next/image?url=https%3A%2F%2Fdirectus-production-8ad9.up.railway.app%2Fassets%2F28ed0c83-f4b1-49e6-9646-a02ee818881f%3Fkey%3Doptimised&w=1920&q=75',
        width: 800,
        height: 600,
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        <div className="pt-10 min-h-[calc(100vh-300px)]">{children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
